name: Update MongoDB

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:
    branches:
      - main 

permissions:
  contents: write  # Allow the workflow to write to the repository

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 feedparser pymongo pandas  

      - name: Run update script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          RSS_SOURCES_COLLECTION_NAME: ${{ secrets.RSS_SOURCES_COLLECTION_NAME }}
        run: python update_mongodb.py

  deploy:
    runs-on: ubuntu-latest
    needs: update  # Ensure this job runs after the update job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build static files
        run: |
          ./start.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static  # Adjust this if your static files are in a different directory
