name: Update MongoDB
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:
    branches:
      - main 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 feedparser pymongo pandas  
      - name: Run update script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
          RSS_SOURCES_COLLECTION_NAME: ${{ secrets.RSS_SOURCES_COLLECTION_NAME }}
        run: python update_mongodb.py
